# File Structure
#
# The "general" section contains flags that will always be used for slicing, each parameter must hence be a single value

[printer]
name = VoronV24
bounding_box = 340,340,300

[general]
perimeter_acceleration = 4000
solid_infill_acceleration = 4000
infill_acceleration = 4000
bridge_acceleration = 4000
first_layer_acceleration = 4000
travel_acceleration = 4000
default_acceleration = 4000
max_print_speed = 125
travel_speed = 300
travel_speed_z = 15
first_layer_speed = 30
perimeter_speed = 100
small_perimeter_speed = 40
external_perimeter_speed = 40
infill_speed = 125
solid_infill_speed = 120
top_solid_infill_speed = 50
support_material_speed = 90
bridge_speed = 60
gap_fill_speed = 40

# Other flags: only one section will be used, based on the `--slice-section` flag of the main slicing python script

[paperDistribution]
fill_density = DrawDensityFromType
fill_pattern = DrawTypeFrom:90:10
fill_angle = range:0:90
material = random:pla:abs:pet

[optimTest]
fill_density = 15%
fill_pattern = expand:rectilinear:grid:honeycomb
fill_angle = expand:0:1:2:3:4:5:6:7:8:9:10:11:12:13:14:15:16:17:18:19:20:21:22:23:24:25:26:27:28:29:30:31:32:33:34:35:36:37:38:39:40:41:42:43:44:45:46:47:48:49:50:51:52:53:54:55:56:57:58:59:60:61:62:63:64:65:66:67:68:69:70:71:72:73:74:75:76:77:78:79:80:81:82:83:84:85:86:87:88:89

[randomInfill]
fill_density = funcrange_fillrange:5:80
fill_pattern = expand:rectilinear:alignedrectilinear:grid:triangles:stars:cubic:line:concentric:honeycomb:3dhoneycomb:gyroid:hilbertcurve:archimedeanchords:octagramspiral:adaptivecubic:supportcubic:lightning:zigzag
fill_angle = range:0:90

[infillTypeTest]
fill_density = 20%
fill_pattern = expand:rectilinear:alignedrectilinear:grid:triangles:stars:cubic:line:concentric:honeycomb:3dhoneycomb:gyroid:hilbertcurve:archimedeanchords:octagramspiral:adaptivecubic:supportcubic:lightning:zigzag
fill_angle = range:0:90

[infillDensityTest]
fill_density = expand:5%:6%:7%:8%:9%:10%:11%:12%:13%:14%:15%:16%:17%:18%:19%:20%:21%:22%:23%:24%:25%:26%:27%:28%:29%:30%:31%:32%:33%:34%:35%:36%:37%:38%:39%:40%:41%:42%:43%:44%:45%:46%:47%:48%:49%:50%:51%:52%:53%:54%:55%:56%:57%:58%:59%:60%:61%:62%:63%:64%:65%:66%:67%:68%:69%:70%:71%:72%:73%:74%:75%:76%:77%:78%:79%
fill_pattern = expand:rectilinear:alignedrectilinear:grid:triangles:stars:cubic:line:concentric:honeycomb:3dhoneycomb:gyroid:hilbertcurve:archimedeanchords:octagramspiral:adaptivecubic:supportcubic:lightning:zigzag
fill_angle = range:0:90

[testExponDensityDistr]
fill_density = funcrange_exprange:5:80
fill_pattern = expand:rectilinear:alignedrectilinear:grid:triangles:stars:cubic:line:concentric:honeycomb:3dhoneycomb:gyroid:hilbertcurve:archimedeanchords:octagramspiral:adaptivecubic:supportcubic:lightning:zigzag
fill_angle = range:0:90

[testMaterialRandom]
fill_density = funcrange_fillrange:5:80
fill_pattern = random:rectilinear:alignedrectilinear:grid:triangles:stars:cubic:line:concentric:honeycomb:3dhoneycomb:gyroid:hilbertcurve:archimedeanchords:octagramspiral:adaptivecubic:supportcubic:lightning:zigzag
fill_angle = range:0:90
material = random:pla:flex:petg

[testInfillRotation]
fill_density = 20%
fill_pattern = expand:rectilinear:grid
fill_angle = expand:0:1:2:3:4:5:6:7:8:9:10:11:12:13:14:15:16:17:18:19:20:21:22:23:24:25:26:27:28:29:30:31:32:33:34:35:36:37:38:39:40:41:42:43:44:45:46:47:48:49:50:51:52:53:54:55:56:57:58:59:60:61:62:63:64:65:66:67:68:69:70:71:72:73:74:75:76:77:78:79:80:81:82:83:84:85:86:87:88:89

# Non-fixed flags

[basedon_material]